version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    # Definir el runtime adecuado
  pre_build:
    commands:
      - cd talleres/06/
      - pip install -r requirements.txt --use-feature=2020-resolver
  build:
    commands:
      - pytest
