version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    # Definir el runtime adecuado
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - pytest
